# 前端异常错误处理

## 前言

js报错导致后面的语句不执行，如下面 a.b 不存在，浏览器报错，后续代码不执行，之前的代码是生效的，如果志强事件绑定上去的话也不会影响

```js
console.log(a.b)
// ...
```

### try catch

无法捕获异步请求

```js
try{
    setTimeout(() => {
    console.log(a.b)
    }, 100)
}catch(err){console.log(err)}

```

### unhandledrejection

let ajax  = new XMLHttpRequest()
xmlHttp.open(opt.method, opt.url, opt.async);
xmlHttp.readyState
xmlHttp.onreadystatechange = function () {
        if (xmlHttp.readyState == 4 ) {
          if((xmlHttp.status >= 200 || xmlHttp.status < 300 || xmlHttp.status == 304)){
            resolve(xmlHttp.responseText)
          }else{
            reject(xmlHttp.responseText)
          }
        }
      };
xmlHttp.send(postData);

## 总结

### 参考文献

1. <https://developer.mozilla.org/zh-CN/docs/Web/Events/unhandledrejection>
